DWAPlannerROS:

  # Robot Configuration Parameters
   max_vel_x: 1
   max_vel_x_backwards: 0.2
   min_vel_x: 0.1

   max_trans_vel: 1
   min_trans_vel: 0.1

   max_vel_y: 0.0
   min_vel_y: 0.0

  max_trans_vel: 1.0
  min_trans_vel: 0.0

  max_rot_vel: 0.4 # 1.0
  min_rot_vel: 0.2 # could set this lower


  acc_lim_x: 0.2
  acc_lim_th: 0.05 # 1.0
  acc_lim_y: 0.0 # diff drive robot


  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 3
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 30
  controller_frequency: 5
  #meter_scoring: true
  #penalize_negative_x: false

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.01
  forward_point_distance: 0 # Default 0.325
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  #cheat_factor: 2
  #scaled_path_factor: 0.75

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Global Plan Parameters
  prune_plan: true
