global_costmap:
  global_frame : map
  update_frequency: 4.5
  publish_frequency: 4.5
  transform_tolerance: 0.2
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  static_map: true
  rolling_window: true
  inflation_radius: 0.2
  resolution: 0.1
