local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.1
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  origin_x: -2.5
  origin_y: -2.5
  resolution: 0.1
  inflation_radius: 0.1
